#!/usr/bin/env bash
# Generates docs/traceability-matrix.md (SRS §36, TRS §45, unit U61): every
# FR-ID in docs/SRS.md, cross-referenced against real repo content, not a
# hand-maintained document. NFR-* IDs are deliberately excluded — SRS §36's
# own wording is "every FR-ID," and this project's IDs share the "FR-"
# suffix as a literal substring of "NFR-", so exclusion needs an explicit
# word-boundary check, not just a plain grep.
#
# Three-tier status, not a binary pass/fail: CLAUDE.md's own session-hygiene
# section says FR-IDs are referenced "sparingly in code comments and
# explicitly in the tests that cover them" — the convention was never "tag
# every implementing file," so a reference existing only outside a test
# file is genuinely ambiguous to a grep-based tool (it may well have real,
# passing, just-untagged test coverage) and is reported as such rather than
# asserted either way.
#   OK                  — at least one reference inside a real test (a file
#                          under a tests/ directory, or a reference that
#                          falls after a source file's own last
#                          `#[cfg(test)]` marker — this codebase's own
#                          established inline-test-module convention).
#   NEEDS-VERIFICATION   — referenced somewhere, but never inside a test.
#   MISSING              — zero references anywhere in the repo.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="docs/traceability-matrix.md"
SEARCH_DIRS=(rust_core console/lib console/test docs/adr migrations)
GREP_FILTERS=(--include='*.rs' --include='*.dart' --include='*.md' --include='*.sql'
  --exclude-dir=target --exclude-dir=build --exclude-dir=.dart_tool)

is_test_reference() {
  local file="$1" line="$2"
  case "$file" in
    */tests/*|console/test/*) return 0 ;;
    # The `#[cfg(test)]`-fallback below only makes sense for real Rust
    # source — unit U62's own real discovery: an ADR that merely
    # *describes* this exact heuristic in prose (quoting the literal
    # string `#[cfg(test)]`) otherwise makes every later FR-ID reference
    # in that same doc misclassify as "after the test marker."
    *.rs) : ;;
    *) return 1 ;;
  esac
  local last_cfg
  last_cfg=$(grep -n '#\[cfg(test)\]' "$file" 2>/dev/null | tail -1 | cut -d: -f1 || true)
  [ -n "${last_cfg:-}" ] && [ "$line" -gt "$last_cfg" ]
}

{
  echo "# FR-ID Traceability Matrix"
  echo
  echo "Generated by \`scripts/generate-traceability-matrix.sh\` (SRS §36, TRS"
  echo "§45, unit U61) — do not edit by hand; regenerate and commit instead."
  echo "Checked for drift by \`scripts/check-fr-id-traceability.sh\`."
  echo
  echo "| FR-ID | Requirement | Unit | Module | Test | Status |"
  echo "|---|---|---|---|---|---|"

  ok=0
  needs=0
  missing=0
  total=0

  while IFS= read -r reqline; do
    fr=$(echo "$reqline" | grep -oE '^FR-[A-Z]+-[0-9]+')
    # Not truncated: a byte-oriented `cut -c` in this environment split
    # multi-byte UTF-8 characters (SRS.md's own em-dashes etc.) mid-
    # sequence, corrupting the generated file — full text is safer than
    # a byte-unsafe truncation.
    text=$(echo "$reqline" | sed -E "s/^${fr}:[[:space:]]*//")
    total=$((total + 1))

    matches=$(grep -rn "$fr" "${SEARCH_DIRS[@]}" "${GREP_FILTERS[@]}" 2>/dev/null || true)

    if [ -z "$matches" ]; then
      echo "| $fr | $text | n/a | n/a | n/a | MISSING |"
      missing=$((missing + 1))
      continue
    fi

    unit=$(echo "$matches" | grep -oE '\bU[0-9]+\b' | head -1 || true)
    [ -z "$unit" ] && unit="n/a"

    module=""
    test_file=""
    while IFS= read -r m; do
      f="${m%%:*}"
      rest="${m#*:}"
      l="${rest%%:*}"
      if is_test_reference "$f" "$l"; then
        [ -z "$test_file" ] && test_file="$f"
      else
        [ -z "$module" ] && module="$f"
      fi
    done <<<"$matches"

    if [ -n "$test_file" ]; then
      ok=$((ok + 1))
      module="${module:-$test_file}"
      echo "| $fr | $text | $unit | \`$module\` | \`$test_file\` | OK |"
    else
      needs=$((needs + 1))
      echo "| $fr | $text | $unit | \`$module\` | none | NEEDS-VERIFICATION |"
    fi
  done < <(grep -noE '(^|[^N])FR-[A-Z]+-[0-9]+\*{0,2}:.*' docs/SRS.md \
    | sed -E 's/^[0-9]+:[^F]*//' | sed -E 's/\*\*//g')

  echo
  echo "**Summary**: $ok OK, $needs NEEDS-VERIFICATION, $missing MISSING (of $total total FR-IDs)."
} >"$OUT"

echo "Wrote $OUT"
